import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "@/app/globals.css";
import { Navbar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

type Props = Readonly<{
  children: ReactNode;
}>;

const RootLayout = ({ children }: Props) => (
  <html lang="en" className="h-full">
    <body
      className={cn("relative h-full font-sans antialiased", inter.className)}
    >
      <main className="relative flex flex-col m-h-screen">
        <Navbar />
        <div className="flex-grow flex-1">{children}</div>
      </main>
    </body>
  </html>
);

export default RootLayout;
